# Generated by Django 4.1.10 on 2023-08-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link',
            new_name='redirections',
        ),
    ]
