# Generated by Django 4.1.10 on 2023-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_rename_link_redirections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='redirections',
        ),
    ]
